### ISSUE TITLE
New QR code

### ISSUE THREAD

**Issue by denysvitali** [denysvitali/covid-cert-analysis#8]
I can't update the repo, but this is a new example of a QR code that is marked as valid on the EU apps (including Swiss Covid app). Thanks @Maxmontgelas

<img width="367" alt="bbtest" src="https://user-images.githubusercontent.com/4939519/139872594-e0860024-43d5-4d7d-8990-2dc71c74f9e7.png">

**Comment by Maxmontgelas** [comment]
I wish it wasn't. but secretly I am happy it does for all the wrong reasons.
